name: Deploy to Cloud TMS
on:
  push:
    branches:
    - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: Extract branch name
          shell: bash
          run: |
            echo "branch=${GITHUB_HEAD_REF}"
            echo "${GITHUB_REF#refs/heads/}"
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
            echo ${{ github.workspace }}
          id: extract_branch 
        - name: CURL
          run: |
            curl -V
          # TOKEN=$(curl -s -X POST -u "sb-d7d48e38-4683-463a-a607-4949e6146ca1!b153390|alm-ts-backend!b1603:0b907e0a-0b16-4130-85b0-db2eea982c4e$IJf4Vk4IBnvrrrpc4hvXn6WYG4NYAaAXofGQig-NbC4=" -d "grant_type=client_credentials&response_type=token" https://96468441trial.authentication.us10.hana.ondemand.com/oauth/token | sed -n '/ *"access_token": *"/ {s///; s/{//g ;s/".*//; p; }')                  
#TOKEN=$(curl -XPOST -H 'Accept: application/json' -u 'sb-21afe38d-ae8b-4d6f-9414-e352853ddf0e!b185374|alm-ts-backend!b1603:73a7dbc1-3dd5-4c67-a2f1-1d234a84f8ba$MFgjO37Ff6mErxiJNowC_k9T52qcUA5BmthRHDkfvNA=' -H 'Content-Type: application/x-www-form-urlencoded' 'https://70f0e8b1trial.authentication.us10.hana.ondemand.com/oauth/token?grant_type=client_credentials&response_type=token' | sed -n '/ *"access_token": *"/ {s///; s/{//g ;s/".*//; p; }')
        - name: Token
          run: |        
           TOKEN=$(curl -XPOST -I -H 'Accept: application/json' -u 'sb-21afe38d-ae8b-4d6f-9414-e352853ddf0e!b185374|alm-ts-backend!b1603:73a7dbc1-3dd5-4c67-a2f1-1d234a84f8ba$MFgjO37Ff6mErxiJNowC_k9T52qcUA5BmthRHDkfvNA=' -H 'Content-Type: application/x-www-form-urlencoded' 'https://70f0e8b1trial.authentication.us10.hana.ondemand.com/oauth/token?grant_type=client_credentials&response_type=token')
           echo $TOKEN
          #BODY=$(curl -s --location --request POST 'https://70f0e8b1trial.authentication.us10.hana.ondemand.com/v2/files/upload' --header "Authorization: Bearer $TOKEN" -F 'file=@${{ github.workspace }}/githcicd_0.0.1.mtar' )
          # echo $BODY
    
