name: Deploy to Cloud TMS
on:
  push:
    branches:
    - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: CURL
          run: curl -V
